### ISSUE TITLE
read_only: true causes "Unpermitted parameter" error

### ISSUE THREAD

**Issue by rkumar** [adrianthedev/avobookr#3]
Create Booking form. Avo v2.29.1. Rails 7.0.4.3. ruby 3.1.2p20

When I add the `read_only: true` in the line:   `field :user, as: :belongs_to, default: -> { Avo::App.context[:current_user].id }, readonly: true` while creating a new booking, i get an error that the "User must exist", even though the correct user is displayed. 

On the console I get this error: "Unpermitted parameter: :user_id." 
If I remove the "read_only: true" then I am able to successfully save the booking with the same user. 
I have tried with both avo v2.29.0 and 2.29.1 (latest). 

Finally, I went through the source code of the `base_controller.rb`. I have overridden method `extra_params` in my controller and added :user_id to the array. Now it works, but I find a message in red color on the console: "Unpermitted parameters: :room_id, :booked_at, :booked_for. Context: {  }". This is strange since it _is_ working, and I am printing @permitted_params on the console and it does include the relevant fields. Thanks.

**Comment by adrianthedev** [comment]
Hey @rkumar.

The video and Avo version used in the video was made on an older version where `readonly` worked differently.

We changed that so we can improve security. Here's a bit of detail on why that changed.

<img width="728" alt="CleanShot 2023-04-03 at 22 48 13@2x" src="https://user-images.githubusercontent.com/1334409/229612018-d35060ca-7b37-49ed-9148-a96d8bdbc6b4.png">

You can use `disabled` instead of `readonly` and it will work like in the video.

The `Unpermitted...` logs may come from somewhere else. We are using `params.permit` multiple times (in resource tools too) and that may output that log, so I wouldn't worry about that.

Please try `disabled` instead of `reaodnly` and let me know if that fixed it for you.

**Comment by rkumar** [comment]
`disabled` worked great. 
Thanks a lot.
